/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Paneles.Paciente;

import Controlador.ListadosConcurrentes;
import Hilos.HilosPaciente;
import Modelo.Paciente;
import Vistas.VentanaInicio;
import Vistas.formatosTextArea;

/**
 *
 * @author daniel
 */
public class PanelAltasPaciente extends javax.swing.JPanel {
    ListadosConcurrentes lists;
    VentanaInicio faz;
    /**
     * Creates new form PanelAltasPaciente
     */
    public PanelAltasPaciente(ListadosConcurrentes listas, VentanaInicio fa) {
        this.lists = listas;
        this.faz = fa;
        initComponents();
        CBPersona.setModel(lists.crearModeloComboBox2(lists.getListaPersonas()));
        formatosTextArea.setSoloAlfanumericos(txtNumSeg, 10);
        formatosTextArea.setSoloAlfanumericos(txtAlergias, 450);
        formatosTextArea.setMaxCaracteres(txtGrupSangineo, 4);
        setVaciarComponentes();
        
    }
    public void setVaciarComponentes(){
        txtAlergias.setText("");
        txtGrupSangineo.setText("");
        txtNumSeg.setText("");
        CBPersona.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBPersona = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNumSeg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGrupSangineo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlergias = new javax.swing.JTextArea();
        BReset = new javax.swing.JButton();
        BGuardar = new javax.swing.JButton();

        jLabel1.setText("Añadir paciente");

        jLabel2.setText("Nombre");

        CBPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Numero de seguro");

        jLabel4.setText("Grupo sangineo");

        jLabel5.setText("Alergias");

        txtAlergias.setColumns(20);
        txtAlergias.setRows(5);
        jScrollPane1.setViewportView(txtAlergias);

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        BGuardar.setText("Guardar");
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumSeg)
                            .addComponent(txtGrupSangineo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(BReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BGuardar)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGrupSangineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BReset)
                    .addComponent(BGuardar))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        setVaciarComponentes();
    }//GEN-LAST:event_BResetActionPerformed

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
        boolean n = !(txtAlergias.getText().trim().equals(""));
        boolean n2 = !(txtGrupSangineo.getText().trim().equals(""));
        boolean n3 = !(txtNumSeg.getText().trim().equals(""));
        boolean n4 = !(CBPersona.getSelectedItem() == null);
        if(!n || !n2 || !n3 || !n4){
            faz.ShowMessage("uno o mas campos esta vacio");
        }else{
            int dni = getDNIpersona((String) CBPersona.getSelectedItem());
            Paciente pac = new Paciente(0, dni, txtNumSeg.getText().trim(), txtGrupSangineo.getText().trim(), txtAlergias.getText().trim());
            HilosPaciente hprov = new HilosPaciente(faz, pac);
            hprov.AñadirPaciente();
        }
    }//GEN-LAST:event_BGuardarActionPerformed

    private int getDNIpersona(String personaSelect){
        for (String[] n : lists.getListaPersonas()){
            if(n[1].equalsIgnoreCase(personaSelect)){
                int m = Integer.parseInt(n[0]);
                return m;
            }
        }
        return 0;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton BReset;
    private javax.swing.JComboBox<String> CBPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlergias;
    private javax.swing.JTextField txtGrupSangineo;
    private javax.swing.JTextField txtNumSeg;
    // End of variables declaration//GEN-END:variables
}
