/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Paneles.Cita;

import Controlador.CitaDAO;
import Controlador.ListadosConcurrentes;
import Hilos.HilosCita;
import Vistas.VentanaInicio;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JRadioButton;
import javax.swing.table.TableModel;

/**
 *
 * @author daniel
 */
public class PanelConsultaCita extends javax.swing.JPanel {
    ListadosConcurrentes lists;
    VentanaInicio faz;
    int opcion = 0;
    /**
     * Creates new form PanelConsultaCita
     */
    public PanelConsultaCita(ListadosConcurrentes listas, VentanaInicio fa) {
        this.faz = fa;
        this.lists = listas;
        initComponents();
        BGBusqueda.add(RBBusqEstado);
        BGBusqueda.add(RBBusqNomPac);
        BGBusqueda.add(RBBusqNomPersonal);
        CBEstado.setModel(lists.crearModeloComboBox(lists.getListaEstados()));
        CBPaciente.setModel(lists.crearModeloComboBox2(lists.getListaPacientes()));
        CBPersonal.setModel(lists.crearModeloComboBox2(lists.getListaPersonal()));
        setVaciarComponentes();
        
    }
    
    public void setVaciarComponentes(){
        CBEstado.setSelectedItem(null);
        CBPaciente.setSelectedItem(null);
        CBPersonal.setSelectedItem(null);
        disableSelectRB(BGBusqueda);
    }
    private void setSelect(JRadioButton seleccion){
        if (seleccion == RBBusqEstado){
            opcion = 1;
        }else if (seleccion == RBBusqNomPac){
            opcion = 2;
        }else if (seleccion == RBBusqNomPersonal){
            opcion = 3;
        }
    }
    
    private void disableSelectRB(ButtonGroup buttonGroup){
            buttonGroup.clearSelection();
        
    }
    
    
    
 public void setEnableRBFromGroup(ButtonGroup grupo) {                           // Metodo para abilitar/desbilitar campos de texto en base a RB dentro de un buttonGroup
    // 1. Obtener el ButtonModel seleccionado
    ButtonModel modeloSeleccionado = grupo.getSelection();

    if (modeloSeleccionado != null) {
        // 2. Iterar sobre los botones del grupo para encontrar el JRadioButton
        Enumeration<AbstractButton> botones = grupo.getElements();
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.getModel() == modeloSeleccionado) {
                // Se encontró el JRadioButton seleccionado
                if (boton instanceof JRadioButton) {
                    JRadioButton rbSeleccionado = (JRadioButton) boton;
                    
                   setSelect(rbSeleccionado);

                    break; // Salir del bucle una vez encontrado
                }
            }
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGBusqueda = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResult = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        RBBusqNomPersonal = new javax.swing.JRadioButton();
        RBBusqNomPac = new javax.swing.JRadioButton();
        RBBusqEstado = new javax.swing.JRadioButton();
        CBPersonal = new javax.swing.JComboBox<>();
        CBPaciente = new javax.swing.JComboBox<>();
        CBEstado = new javax.swing.JComboBox<>();
        BBuscar = new javax.swing.JButton();
        BReset = new javax.swing.JButton();

        jLabel1.setText("Consultar citas");

        tablaResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaResult);

        jLabel2.setText("Resultados");

        RBBusqNomPersonal.setText("Nombre del doctor");

        RBBusqNomPac.setText("Nombre del paciente");

        RBBusqEstado.setText("Estado");

        CBPersonal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BBuscar.setText("Buscar");
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RBBusqNomPac)
                            .addComponent(RBBusqNomPersonal)
                            .addComponent(RBBusqEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBEstado, 0, 100, Short.MAX_VALUE)
                            .addComponent(CBPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBPersonal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BBuscar)
                            .addComponent(BReset))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBusqNomPersonal)
                    .addComponent(CBPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBusqNomPac)
                    .addComponent(CBPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBusqEstado)
                    .addComponent(CBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        setVaciarComponentes();
    }//GEN-LAST:event_BResetActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        setEnableRBFromGroup(BGBusqueda);
        HilosCita hcit = new HilosCita(faz, null);
        if (opcion >=1 && opcion <= 3){
                String criterio= "";
                switch (opcion) {
                    case 1 -> criterio = (String) CBEstado.getSelectedItem();
                    case 2 -> criterio = (String) CBPaciente.getSelectedItem();
                    case 3 -> criterio = (String) CBPersonal.getSelectedItem();
                }
                criterio = returnLocarVariable(criterio, opcion);
                hcit.selectHiloBusq(criterio,opcion, tablaResult);
        }else{
            faz.ShowMessageFeerback("selecciona el metodo de busqueda");
        }
    }//GEN-LAST:event_BBuscarActionPerformed

    private String returnLocarVariable(String criterio, int o){
        ArrayList<String[]> pac = lists.getListaPacientesNom();
        ArrayList<String[]> per = lists.getListaPersonalNom();
        ArrayList<String[]> pac2 = lists.getListaPacientes();
        ArrayList<String[]> per2 = lists.getListaPersonal();
        String sal = criterio;
        String id = "";
        if(o == 2){
            for (String[] n : pac2){
                if(n[1].equalsIgnoreCase(criterio)){
                    id = n[0];
                    System.out.println(id);
                    break;
                }
            }
            for (String[] m : pac){
                if(m[0].equalsIgnoreCase(id)){
                    sal = m[1];
                    System.out.println(sal);
                    break;
                }
            }
        }
        else if (o==3){
            for (String[] m : per2){
                if(m[1].equalsIgnoreCase(criterio)){
                    id = m[0];
                    System.out.println(id);
                    break;
                }
            }
            for (String[] n : per){
                if(n[0].equalsIgnoreCase(id)){
                    sal = n[1];
                    System.out.println(sal);
                    break;
                }
            }
        }
        return sal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscar;
    private javax.swing.ButtonGroup BGBusqueda;
    private javax.swing.JButton BReset;
    private javax.swing.JComboBox<String> CBEstado;
    private javax.swing.JComboBox<String> CBPaciente;
    private javax.swing.JComboBox<String> CBPersonal;
    private javax.swing.JRadioButton RBBusqEstado;
    private javax.swing.JRadioButton RBBusqNomPac;
    private javax.swing.JRadioButton RBBusqNomPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaResult;
    // End of variables declaration//GEN-END:variables
}
