/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Paneles.Cita;
import Controlador.ListadosConcurrentes;
import Hilos.HilosCita;
import Modelo.Cita;
import Vistas.VentanaInicio;
import Vistas.formatosTextArea;

/**
 *
 * @author daniel
 */
public class PanelAltasCita extends javax.swing.JPanel {
    ListadosConcurrentes lists;
    VentanaInicio interfaz;
    /**
     * Creates new form PanelAltasCita
     */
    public PanelAltasCita(ListadosConcurrentes listas, VentanaInicio faz) {
        this.lists = listas;
        this.interfaz = faz;
        initComponents();
        formatosTextArea.FormatoFecha(txtFecha);
        formatosTextArea.FormatoHora(txtHora);
        formatosTextArea.setSoloLetras(txtMotivo, 70);
        CBEstado.setModel(lists.crearModeloComboBox(lists.getListaEstados()));
        CBPacientes.setModel(lists.crearModeloComboBox2(lists.getListaPacientes()));
        CBPersonal.setModel(lists.crearModeloComboBox2(lists.getListaPersonal()));
        //CBPacientes.setEditable(true);
        //CBPersonal.setEditable(true);
        //formatosTextArea.attachFilter(CBPersonal);
        //formatosTextArea.attachFilter(CBPacientes);
        
        
        
        
    }
    
    public boolean baiter(String valo, int listado){
        if(listado == 1){
           for (String[] val : lists.getListaPacientes()){
            if (val[1].equalsIgnoreCase(valo)){
                System.out.println("Coincidencia");
                System.out.println(val[0]);
                return true;
            }
        }
        }else{
            for (String[] val : lists.getListaPersonal()){
            if (val[1].equalsIgnoreCase(valo)){
                System.out.println("Coincidencia");
                System.out.println(val[0]);
                return true;
            }
        }
        }
        return false;
    }
    
    public void SetVaciarComponentes(){
        CBPacientes.setSelectedItem(null);
        CBPersonal.setSelectedItem(null);
        CBEstado.setSelectedIndex(0);
        txtFecha.setText("");
        txtHora.setText("");
        txtMotivo.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBPersonal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CBPacientes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CBEstado = new javax.swing.JComboBox<>();
        BReset = new javax.swing.JButton();
        BGuardar = new javax.swing.JButton();
        txtHora = new javax.swing.JFormattedTextField();

        jLabel1.setText("Añadir cita");

        jLabel2.setText("Doctor");

        CBPersonal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Paciente");

        CBPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Fecha");

        jLabel5.setText("Hora");

        jLabel6.setText("Motivo");

        jLabel7.setText("Estado");

        CBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEstadoActionPerformed(evt);
            }
        });

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        BGuardar.setText("Guardar");
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBPacientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBPersonal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha)
                            .addComponent(txtMotivo)
                            .addComponent(CBEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(BReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BGuardar)))
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BReset)
                    .addComponent(BGuardar))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CBEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEstadoActionPerformed

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
        boolean n = CBEstado.getSelectedItem() == null;
        boolean n2= CBPacientes.getSelectedItem() == null;
        boolean n3= CBPersonal.getSelectedItem() == null;
        boolean n4 = !lists.fechaValida(txtFecha.getText().trim());
        boolean n5 = !lists.horaValida(txtHora.getText().trim());
        boolean n6 = txtMotivo.getText().trim().equals("");
        
        if (n || n2 || n3 || n4 || n5 || n6){
            String mensaje = "";
            if (n4 || n5){
                if(n4){
                    mensaje = mensaje + "Fecha mal escrita o vacia \n";
                }else{
                    mensaje = mensaje+ "Hora mal escrita o vacia \n";
                }
            }
            if (n || n2 || n3 || n6){
                mensaje = mensaje + "uno o mas campos vacios";
            }
            interfaz.ShowMessage(mensaje);
        }else{
            String pac = (String) CBPacientes.getSelectedItem();
            String per = (String) CBPersonal.getSelectedItem();
            int ipac = getidPac(pac);
            int iper = getidPer(per);
            Cita ci = new Cita(0, ipac, iper, txtFecha.getText().trim(), txtHora.getText().trim(), txtMotivo.getText().trim(), (String) CBEstado.getSelectedItem());
            HilosCita Hcit = new HilosCita(interfaz, ci);
            Hcit.AñadirCita();
            
            SetVaciarComponentes();
        }
        
    }//GEN-LAST:event_BGuardarActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        SetVaciarComponentes();
    }//GEN-LAST:event_BResetActionPerformed

    private int getidPer(String perso){
        int i = 0;
        for (String[] n : lists.getListaPersonal()){
            if (n[1].equalsIgnoreCase(perso)){
                i = Integer.parseInt(n[0]);
                break;
            }
        }
        return i;
    }
    
    private int getidPac(String perso){
        int i = 0;
        for (String[] n : lists.getListaPacientes()){
            if (n[1].equalsIgnoreCase(perso)){
                i = Integer.parseInt(n[0]);
                break;
            }
        }
        return i;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton BReset;
    private javax.swing.JComboBox<String> CBEstado;
    private javax.swing.JComboBox<String> CBPacientes;
    private javax.swing.JComboBox<String> CBPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
