/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Paneles.Personal;

import Controlador.ListadosConcurrentes;
import Hilos.HilosPersonal;
import Modelo.Persona;
import Modelo.Personal;
import Vistas.*;
import java.math.BigDecimal;
import java.util.ArrayList;

/**
 *
 * @author daniel
 */
public class PanelAltasPersonal extends javax.swing.JPanel {
    ListadosConcurrentes lists;
    VentanaInicio faz;
    boolean siPersona = false;
    /**
     * Creates new form PanelAltasPersonal
     */
    public PanelAltasPersonal(ListadosConcurrentes listas, VentanaInicio fa) {
        this.lists = listas;
        this.faz = fa;
        initComponents();
        
        formatosTextArea.setSoloLetras(txtRol, 70);
        formatosTextArea.setSoloLetras(txtDepart, 70);
        formatosTextArea.setSoloLetras(txtEspecialidad, 70);
        formatosTextArea.FormatoSalario(txtSalario);
        formatosTextArea.setSoloLetras(txtnombres, 70);
        formatosTextArea.setSoloLetras(txtPAP, 45);
        formatosTextArea.setSoloLetras(txtSAP, 45);
        formatosTextArea.FormatoFecha(txtFechaNaci);
        formatosTextArea.FormatoTelefono(txtTelefono);
        
        CBPersona.setModel(lists.crearModeloComboBox2(lists.getListaPersonas()));
        setVaciarComponentes();
    }
    
    public void setVaciarComponentes(){
        txtDepart.setText("");
        txtEspecialidad.setText("");
        txtRol.setText("");
        txtSalario.setText("");
        txtnombres.setText("");
        txtPAP.setText("");
        txtSAP.setText("");
        txtFechaNaci.setText("");
        txtTelefono.setText("");
        CBPersona.setSelectedItem(null);
        enableOpcionADDPersona(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBPersona = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDepart = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BGuardar = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JFormattedTextField();
        ChBEnablePersona = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtPAP = new javax.swing.JTextField();
        txtSAP = new javax.swing.JTextField();
        txtFechaNaci = new javax.swing.JFormattedTextField();
        txtTelefono = new javax.swing.JFormattedTextField();

        setOpaque(false);

        jLabel1.setText("Añadir personal");

        jLabel2.setText("Persona");

        CBPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Rol");

        jLabel4.setText("Departamento");

        jLabel5.setText("Especialidad");

        BGuardar.setText("Guardar");
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        jLabel6.setText("Salario");

        ChBEnablePersona.setText("Añadir aparte");
        ChBEnablePersona.setActionCommand("");
        ChBEnablePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChBEnablePersonaActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombres");

        jLabel8.setText("Primer apellido");

        jLabel9.setText("Segundo apellido");

        jLabel10.setText("Fecha de nacimiento");

        jLabel11.setText("Telefono de contacto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(367, 367, 367))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CBPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRol)
                                    .addComponent(txtDepart)
                                    .addComponent(txtEspecialidad)
                                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtFechaNaci)
                                    .addComponent(txtSAP)
                                    .addComponent(txtPAP)
                                    .addComponent(txtnombres)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(338, 338, 338)
                                .addComponent(ChBEnablePersona))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(BReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BGuardar)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChBEnablePersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BGuardar)
                    .addComponent(BReset))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        setVaciarComponentes();
    }//GEN-LAST:event_BResetActionPerformed

    private void enableOpcionADDPersona(boolean si){
        CBPersona.setEnabled(!si);
        txtnombres.setEditable(si);
        txtPAP.setEditable(si);
        txtSAP.setEditable(si);
        txtFechaNaci.setEditable(si);
        txtTelefono.setEditable(si);
    }
    
    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
        boolean n = txtDepart.getText().trim().equals("");
        boolean n2 = txtEspecialidad.getText().trim().equals("");
        boolean n3 = txtRol.getText().trim().equals("");
        boolean n4 = txtSalario.getText().trim().equals("");
        boolean n5 = CBPersona.getSelectedItem() == null;
        boolean n6;
        boolean n7 = ChBEnablePersona.isSelected();
        BigDecimal salario = new BigDecimal("0");
        try {
            salario = new BigDecimal(txtSalario.getText().trim());
            n6 = salario.signum() == 1;
        } catch (NumberFormatException e) {
            // Manejo de errores: si el String no es un número válido.
            System.err.println("Error: El String no es un formato numérico válido.");
            n6 = false;
        }
        if (n7) n5 = false;
        if(n || n2 || n3 || n4 || n5){
            faz.ShowMessage("uno o mas campos estan vacios");
            if(!n6){
                faz.ShowMessage("salario no valido");
            }
        }else{
            if (!siPersona){
                String nombre =(String) CBPersona.getSelectedItem();
                int dni = esta(nombre);
                Personal perso = new Personal(0,dni , txtRol.getText().trim(), txtDepart.getText().trim(), txtEspecialidad.getText().trim(), salario );
                HilosPersonal per = new HilosPersonal(faz, perso);
                per.AñadirPersonal();
            }else{
                boolean m = !txtnombres.getText().trim().equals("");
                boolean m2 = !txtPAP.getText().trim().equals("");
                boolean m3 = !txtSAP.getText().trim().equals("");
                boolean m4 = !lists.fechaValida(txtFechaNaci.getText().trim());
                //boolean m5 = 
                
                if (m || m2 || m3 || m4){
                    Personal perso = new Personal(0,0 , txtRol.getText().trim(), txtDepart.getText().trim(), txtEspecialidad.getText().trim(), salario );
                    Persona p = new Persona(0, txtnombres.getText().trim(), txtPAP.getText().trim(), txtSAP.getText().trim(), txtFechaNaci.getText().trim(), txtTelefono.getText().trim());
                    HilosPersonal per = new HilosPersonal(faz, perso);
                    per.AñadirPersonalYPersona(p);
                    lists.actualizarPersonas();
                    lists.actualizarPersonal();
                }

            }
        }
        
    }//GEN-LAST:event_BGuardarActionPerformed

    private void ChBEnablePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChBEnablePersonaActionPerformed
        boolean addPerso = ChBEnablePersona.isSelected();
        siPersona = addPerso;
        enableOpcionADDPersona(addPerso);
    }//GEN-LAST:event_ChBEnablePersonaActionPerformed

    private int esta (String nom){
        for (String[] n : lists.getListaPersonas()){
            if (n[1].equalsIgnoreCase(nom)){
                int  m = Integer.parseInt(n[0]);
                return m;
            }
        }
        return 0;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton BReset;
    private javax.swing.JComboBox<String> CBPersona;
    private javax.swing.JCheckBox ChBEnablePersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDepart;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JFormattedTextField txtFechaNaci;
    private javax.swing.JTextField txtPAP;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtSAP;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JFormattedTextField txtTelefono;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
