/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Paneles.Personal;

import Controlador.ListadosConcurrentes;
import Hilos.HilosPersonal;
import Vistas.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author daniel
 */
public class PanelBajasPersonal extends javax.swing.JPanel {
    ListadosConcurrentes lists;
    VentanaInicio faz;
    boolean busco = false;
    HilosPersonal hper;
    /**
     * Creates new form PanelBajasPersonal
     */
    public PanelBajasPersonal(ListadosConcurrentes listas, VentanaInicio fa) {
        this.lists = listas;
        this.faz = fa;
        initComponents();
        formatosTextArea.setSoloLetras(txtbusqNombre, 70);
        hper = new HilosPersonal(faz, null);
        setVaciarComponentes();
        
    }
    public void setVaciarComponentes(){
        txtbusqNombre.setText("");
        busco = false;
        tablaDEfault();
    }
    public void tablaDEfault(){
        hper.allPersonal(tablePersonal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbusqNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePersonal = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Eliminar personal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Buscar por nombre");

        txtbusqNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusqNombreKeyReleased(evt);
            }
        });

        tablePersonal.setBackground(new java.awt.Color(245, 245, 245));
        tablePersonal.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        tablePersonal.setForeground(new java.awt.Color(0, 0, 0));
        tablePersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePersonal.setOpaque(false);
        tablePersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePersonalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePersonal);

        jLabel3.setText("Selecciona al personal a eliminar en la lista siguiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbusqNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbusqNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtbusqNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusqNombreKeyReleased
        if (txtbusqNombre.getText().trim().equals("")){
        }else{
            busco = true;
            hper.BuscarCoincidenciaPersonal(tablePersonal, txtbusqNombre.getText().trim());
        }
    }//GEN-LAST:event_txtbusqNombreKeyReleased

    private void tablePersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePersonalMouseClicked
        int filaSeleccionada = tablePersonal.getSelectedRow();
        
        // Verifica que se haya seleccionado una fila válida y que la tabla no tenga el mensaje "no hay datos"
        if (filaSeleccionada >= 0) {
            TableModel model = tablePersonal.getModel();
            
            
            
            Object idObject = model.getValueAt(filaSeleccionada, 0);
            Object nombreObject = model.getValueAt(filaSeleccionada, 1);
            Object PAPObject = model.getValueAt(filaSeleccionada, 2);
            Object SAPObject = model.getValueAt(filaSeleccionada, 3);
            
            // Convertir a String
            String idPersonal = idObject != null ? idObject.toString() : "N/A";
            String nombrePersonal = nombreObject != null ? nombreObject.toString() : "N/A";
            String PAP = PAPObject != null ? PAPObject.toString() : "N/A";
            String SAP = SAPObject != null ? SAPObject.toString() : "N/A";



            // Mensaje de confirmación
            String mensaje = "¿Estás seguro de que deseas eliminar a "+nombrePersonal+" "+PAP+" "+SAP+"?";
            
            // Mostrar la ventana emergente de confirmación
            int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                mensaje, 
                "Confirmar Eliminación", 
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            // Procesar la respuesta del usuario
            if (opcion == javax.swing.JOptionPane.YES_OPTION) {
                
                hper.EliminarPersonal(Integer.parseInt(idPersonal), tablePersonal);
            } else {
                tablePersonal.clearSelection(); //deseleccionar la fila
            }
        }
    }//GEN-LAST:event_tablePersonalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePersonal;
    private javax.swing.JTextField txtbusqNombre;
    // End of variables declaration//GEN-END:variables
}
