/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;


import Controlador.ListadosConcurrentes;
import Vistas.Paneles.Cita.*;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author daniel
 */
public class CitEdit extends javax.swing.JInternalFrame {

    private String PanelAñadir = "CitaAñadir";
    private String PanelConsultar = "CitaConsultar";
    private String PanelModificar = "CitaModificar";
    private JPanel panelDeContenido;
    private CardLayout cardLayout;
    private VentanaInicio faz;
    private ListadosConcurrentes lists;
    
    private PanelAltasCita citAlta;
    private PanelCambiosCita citCambio;
    private PanelConsultaCita citConsult;
    
    /**
     * Creates new form CitEdit
     */
    public CitEdit(VentanaInicio interfaz, ListadosConcurrentes listas) {
        this.faz = interfaz;
        this.lists = listas;
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        iniciarCardLayaout();
        setWindowShow(1);
    }
    
    private void iniciarCardLayaout(){
        this.citAlta = new PanelAltasCita(lists, faz);
        this.citCambio = new PanelCambiosCita(lists, faz);
        this.citConsult = new PanelConsultaCita(lists, faz);
        
        cardLayout = new CardLayout();
        panelDeContenido = new JPanel(cardLayout);
        
        panelDeContenido.add(citAlta, PanelAñadir);
        panelDeContenido.add(citCambio, PanelModificar);
        panelDeContenido.add(citConsult, PanelConsultar);
        
        getContentPane().removeAll(); // quitamos el layout vacío generado por NetBeans
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jToolBar1, BorderLayout.NORTH);
        getContentPane().add(panelDeContenido, BorderLayout.CENTER);
        
        revalidate();
        repaint();
    }
    
    private void showCardLayaout(String namePanel){
        cardLayout.show(panelDeContenido, namePanel);
        if(namePanel.equals(PanelAñadir)){
            citAlta.SetVaciarComponentes();
        }else if (namePanel.equals(PanelModificar)){
        }else if (namePanel.equals(PanelConsultar)){
        }
    }
    
    public void setWindowShow(int numWindow){
        if (numWindow == 1){
            showCardLayaout(PanelAñadir);
        }else if (numWindow == 2){
            showCardLayaout(PanelModificar);
        }else if (numWindow == 4){
            showCardLayaout(PanelConsultar);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        BNewCita = new javax.swing.JButton();
        BModifiCita = new javax.swing.JButton();
        BModifiEstate = new javax.swing.JButton();

        setClosable(true);

        jToolBar1.setRollover(true);

        BNewCita.setText("Nueva");
        BNewCita.setFocusable(false);
        BNewCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNewCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNewCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNewCitaActionPerformed(evt);
            }
        });
        jToolBar1.add(BNewCita);

        BModifiCita.setText("Modificar");
        BModifiCita.setFocusable(false);
        BModifiCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BModifiCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BModifiCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifiCitaActionPerformed(evt);
            }
        });
        jToolBar1.add(BModifiCita);

        BModifiEstate.setText("Consultar citas");
        BModifiEstate.setFocusable(false);
        BModifiEstate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BModifiEstate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BModifiEstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifiEstateActionPerformed(evt);
            }
        });
        jToolBar1.add(BModifiEstate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 451, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNewCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNewCitaActionPerformed
        setWindowShow(1);
    }//GEN-LAST:event_BNewCitaActionPerformed

    private void BModifiCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifiCitaActionPerformed
        setWindowShow(2);
    }//GEN-LAST:event_BModifiCitaActionPerformed

    private void BModifiEstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifiEstateActionPerformed
        setWindowShow(4);
    }//GEN-LAST:event_BModifiEstateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModifiCita;
    private javax.swing.JButton BModifiEstate;
    private javax.swing.JButton BNewCita;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
