/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controlador.ListadosConcurrentes;
import Vistas.Paneles.Personal.*;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JPanel;

/**
 *
 * @author daniel
 */
public class PersoEdit extends javax.swing.JInternalFrame {

    private JPanel panelDeContenido;
    private CardLayout cardLayout;
    private VentanaInicio interfa;
    private ListadosConcurrentes lists;
    
    public final String PanelAlta = "PanelAltaPersona";
    public final String PanelBaja = "PanelBajaPersona";
    
    private PanelAltasPersonal PersoAlta;
    private PanelBajasPersonal persoBaja;
    
    
    /**
     * Creates new form PersoEdit
     */
    public PersoEdit(VentanaInicio inter, ListadosConcurrentes listados) {
        this.interfa = inter;
        this.lists = listados;
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        PersoAlta = new PanelAltasPersonal(lists, interfa);
        persoBaja = new PanelBajasPersonal(lists);
        
        iniciarCardLayout();
    }
    
    
    private void iniciarCardLayout() {
        cardLayout = new CardLayout();
        panelDeContenido = new JPanel(cardLayout);

        panelDeContenido.add(PersoAlta, PanelAlta);
        panelDeContenido.add(persoBaja, PanelBaja);

        getContentPane().removeAll(); // quitamos el layout vacío generado por NetBeans
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jToolBar1, BorderLayout.NORTH);
        getContentPane().add(panelDeContenido, BorderLayout.CENTER);
        
        revalidate();
        repaint();
    }
    protected void setCardLayaout(String namePanel){
        cardLayout.show(panelDeContenido, namePanel);
        if(namePanel.equals(PanelAlta)){
            
        }else if (namePanel.equals(PanelBaja)){
        }
    }
    
    public void setWindowShow(int numVentana){
        if(numVentana == 1){
            setCardLayaout(PanelAlta);
        }else if (numVentana == 2){
            setCardLayaout(PanelBaja);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        BAñadir = new javax.swing.JButton();
        Beliminar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);

        jToolBar1.setRollover(true);

        BAñadir.setText("Añadir");
        BAñadir.setFocusable(false);
        BAñadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAñadir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAñadirActionPerformed(evt);
            }
        });
        jToolBar1.add(BAñadir);

        Beliminar.setText("Eliminar");
        Beliminar.setFocusable(false);
        Beliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Beliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(Beliminar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 466, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarActionPerformed
        setCardLayaout(PanelBaja);
    }//GEN-LAST:event_BeliminarActionPerformed

    private void BAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAñadirActionPerformed
        setCardLayaout(PanelAlta);
    }//GEN-LAST:event_BAñadirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAñadir;
    private javax.swing.JButton Beliminar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
