/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controlador.ListadosConcurrentes;
import Hilos.HilosReportes;
import javax.swing.JTable;

/**
 *
 * @author daniel
 */
public class ReportEdit extends javax.swing.JInternalFrame {
    ListadosConcurrentes lists;
    VentanaInicio faz; 
    HilosReportes HRep;
    int opcion;

    /**
     * Creates new form ReportEdit
     */
    public ReportEdit(VentanaInicio fa) {
        initComponents();
        lists = new ListadosConcurrentes();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        HRep = new HilosReportes(fa);
        this.faz = fa;
        
    }
    
    public void showAltas(){
        HRep.reportesAltas(TablaReportes);
        opcion = 1;
    }
    public void showBajas(){
        HRep.reportesBajas(TablaReportes);
        opcion = 2;
    }
    public void showCambios(){
        HRep.reportesCambios(TablaReportes);
        opcion = 3; 
    }
    
    private void Actualizar(int op){
        switch (op) {
            case 1 -> showAltas();
            case 2 -> showBajas();
            case 3 -> showCambios();
            default -> System.out.print("ninguna coincidencia");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        BAltas = new javax.swing.JButton();
        BBajas = new javax.swing.JButton();
        BCambios = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReportes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jToolBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        BAltas.setBackground(new java.awt.Color(158, 158, 158));
        BAltas.setForeground(new java.awt.Color(38, 50, 56));
        BAltas.setIcon(new javax.swing.ImageIcon(
            new javax.swing.ImageIcon(getClass().getResource("/Recursos/report.png"))
            .getImage()
            .getScaledInstance(24, 24, java.awt.Image.SCALE_SMOOTH)
        ));
        BAltas.setText("Altas");
        BAltas.setFocusable(false);
        BAltas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAltas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAltas(evt);
            }
        });
        jToolBar1.add(BAltas);

        BBajas.setBackground(new java.awt.Color(158, 158, 158));
        BBajas.setForeground(new java.awt.Color(38, 50, 56));
        BBajas.setIcon(new javax.swing.ImageIcon(
            new javax.swing.ImageIcon(getClass().getResource("/Recursos/reporte.png"))
            .getImage()
            .getScaledInstance(24, 24, java.awt.Image.SCALE_SMOOTH)
        ));
        BBajas.setText("Bajas");
        BBajas.setFocusable(false);
        BBajas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BBajas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBajas(evt);
            }
        });
        jToolBar1.add(BBajas);

        BCambios.setBackground(new java.awt.Color(158, 158, 158));
        BCambios.setForeground(new java.awt.Color(38, 50, 56));
        BCambios.setIcon(new javax.swing.ImageIcon(
            new javax.swing.ImageIcon(getClass().getResource("/Recursos/report1.png"))
            .getImage()
            .getScaledInstance(24,24, java.awt.Image.SCALE_SMOOTH)
        ));
        BCambios.setText("Cambios");
        BCambios.setFocusable(false);
        BCambios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BCambios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCambiosActionPerformed(evt);
            }
        });
        jToolBar1.add(BCambios);

        BActualizar.setBackground(new java.awt.Color(158, 158, 158));
        BActualizar.setForeground(new java.awt.Color(38, 50, 56));
        BActualizar.setIcon(new javax.swing.ImageIcon(
            new javax.swing.ImageIcon(getClass().getResource("/Recursos/actuali.png"))
            .getImage()
            .getScaledInstance(24,24, java.awt.Image.SCALE_SMOOTH)
        ));
        BActualizar.setText("Actualizar resultados");
        BActualizar.setFocusable(false);
        BActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(BActualizar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        TablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaReportes.setOpaque(false);
        jScrollPane1.setViewportView(TablaReportes);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showAltas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAltas
        showAltas();
    }//GEN-LAST:event_showAltas

    private void showBajas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBajas
        showBajas();
    }//GEN-LAST:event_showBajas

    private void BCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCambiosActionPerformed
        showCambios();
    }//GEN-LAST:event_BCambiosActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        Actualizar(opcion);
    }//GEN-LAST:event_BActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BAltas;
    private javax.swing.JButton BBajas;
    private javax.swing.JButton BCambios;
    private javax.swing.JTable TablaReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
